[package]
name = "wasm_app2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http_req_wasi = "0.11.1"
rustls = "0.22.2"
wasmedge_wasi_socket = "0.5.3"
